# Site settings
title: *Filipe Portifolio
email: fpinatoaguiar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: tiofih
github_username:  tiofih

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/


